name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build nginx image
      run: docker build -f nginx.dockerfile -t fifi1030/2025cloud:nginx .

    - name: Push nginx image
      run: docker push fifi1030/2025cloud:nginx

    - name: Build flaskapp image
      run: docker build -f app.dockerfile -t fifi1030/2025cloud:flaskapp .

    - name: Push flaskapp image
      run: docker push fifi1030/2025cloud:flaskapp
